
### Get user's ticket 
GET {{BASE_URL}}:{{APP_PORT}}/tickets/

### Add tickets
POST {{BASE_URL}}:{{APP_PORT}}/tickets/
Content-Type: application/json

[
 {
    "price": 14.5,
    "showtimeId": 101,
    "seatNr": 19
 },
 {
    "price": 11.5,
    "showtimeId": 23,
    "seatNr": 13
 }
]
